packages:
  - packages/*
  - apps/*

verifyDepsBeforeRun: false

allowBuilds:
  esbuild: true
  nx: true

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@commercelayer/app-elements'
  - '@commercelayer/sdk'

blockExoticSubdeps: false
