packages:
  - packages/*
  - apps/*

allowBuilds:
  esbuild: true
  nx: true

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@commercelayer/app-elements'
  - '@commercelayer/sdk'
  - '@tanstack/react-table@9.0.0'
  - '@tanstack/table-core@9.0.0'
